# render.yaml
services:
  - type: web
    name: jobtrack-api
    env: node
    region: ohio
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        value: https://jobtrack-app.vercel.app
      - key: ADMIN_INVITE_SECRET
        sync: false
    autoDeploy: true
